packages:
  - packages/js-api-generator
  - packages/config-generator
  - packages/cli-generator
  - packages/tauri-typedoc-theme
  - packages/releases-generator
  - packages/compatibility-table
  - packages/fetch-sponsors
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp

overrides:
  "@astrojs/mdx@^5.0.6": "^7.0.0" # For `starlight-blog@0.26.1`
