const guides = [
  {
    type: 'category',
    label: 'Guides',
    link: { type: 'doc', id: 'guides/readme' },
    items: [
      {
        type: 'autogenerated',
        dirName: 'guides',
      },
    ],
  },
]

const references = [
  {
    type: 'category',
    label: 'References',
    link: { type: 'doc', id: 'references/readme' },
    items: [
      {
        type: 'autogenerated',
        dirName: 'references',
      },
    ],
  },
]

const js = [
  {
    type: 'autogenerated',
    dirName: 'api/js',
  },
]

module.exports = {
  guides,
  references,
  js,
}
