const about = [
  'about/intro',
  'about/architecture',
  'about/security',
  'about/governance',
  'about/book',
  {
    type: 'link',
    label: 'Benchmarks',
    href: '/benchmarks',
  },
]

const docs = [
  {
    'Getting Started': [
      'getting-started/beginning-tutorial',
      'getting-started/setup-linux',
      'getting-started/setup-macos',
      'getting-started/setup-windows',
    ],
    Development: ['development/intro', 'development/development-cycle'],
    Architecture: [
      {
        Patterns: [
          'architecture/patterns/about-patterns',
          'architecture/patterns/hermit',
          'architecture/patterns/bridge',
          'architecture/patterns/cloudish',
          'architecture/patterns/cloudbridge',
          'architecture/patterns/lockdown',
          'architecture/patterns/multiwin',
          'architecture/patterns/glui',
        ],
      },
    ],
    Guides: [
      'guides/cli',
      'guides/command',
      'guides/events',
      'guides/plugin',
      'guides/icons',
      'guides/updater',
      'guides/splashscreen',
      'guides/window-customization',
      'guides/menu',
      'guides/system-tray',
    ],
    Debugging: ['debugging/debugging'],
    Testing: [
      {
        'WebDriver Testing': [
          'testing/webdriver/introduction',
          {
            'Example Application': [
              'testing/webdriver/example/setup',
              'testing/webdriver/example/webdriverio',
              'testing/webdriver/example/selenium',
            ],
          },
          'testing/webdriver/ci',
        ],
      },
    ],
    Building: [
      'building/cross-platform',
      'building/introduction',
      'building/anti-bloat',
      'building/sidecar',
      'building/debian',
      'building/sign-macos',
      'building/sign-windows',
    ],
    Distribution: ['distribution/publishing', 'distribution/updating'],
  },
  'faq',
]

const api = [
  'api/config',
  'api/cli',
  {
    type: 'link',
    label: 'Rust (via Docs.rs)',
    href: 'https://docs.rs/tauri/1.0.0-beta.8/',
  },
  {
    type: 'category',
    label: 'JavaScript / TypeScript',
    link: {
      type: 'doc',
      id: 'api/js/index',
    },
    items: [
      {
        type: 'autogenerated',
        dirName: 'api/js/modules',
      },
    ],
  },
]

const community = ['community/contributor-guide', 'community/ci-cd']

module.exports = {
  about,
  docs,
  api,
  community,
}
