import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type { MarkdownHeading } from 'astro';
import { createMarkdownProcessor } from '@astrojs/markdown-remark';
import ProjectContext from 'virtual:starlight/project-context';

let markdownProcessor: ReturnType<typeof createMarkdownProcessor> | undefined;

function getPermissionsReferencePath(plugin: string) {
  return path.join(
    fileURLToPath(ProjectContext.root),
    'packages/plugins-workspace/plugins',
    plugin,
    'permissions/autogenerated/reference.md'
  );
}

function getMarkdownProcessor() {
  markdownProcessor ??= createMarkdownProcessor();
  return markdownProcessor;
}

export async function getPluginPermissionsMarkdown(plugin: string): Promise<string> {
  const mdPath = getPermissionsReferencePath(plugin);

  try {
    return await fs.readFile(mdPath, 'utf-8');
  } catch (err) {
    console.error(`Error reading file ${mdPath}: ${err}`);
    throw err;
  }
}

export async function renderPluginPermissionsMarkdown(plugin: string): Promise<string> {
  const content = await getPluginPermissionsMarkdown(plugin);
  const md = await getMarkdownProcessor();
  return (await md.render(content)).code;
}

export function addHeadingLinks(code: string): string {
  for (const heading of ['h1', 'h2', 'h3', 'h4']) {
    code = code.replaceAll(
      new RegExp(`<${heading} id="([^"]+)">([\\s\\S]*?)</${heading}>`, 'g'),
      `<${heading} id="$1"><a href="#$1" class="heading-link">$2</a></${heading}>`
    );
  }

  return code;
}

export async function getPluginPermissionTocHeadings(plugin: string): Promise<MarkdownHeading[]> {
  const code = await renderPluginPermissionsMarkdown(plugin);

  return [...code.matchAll(/<h([23]) id="([^"]+)">([\s\S]*?)<\/h\1>/g)].map(
    ([, depth, slug, html]) => ({
      depth: Number(depth),
      slug,
      text: htmlToText(html),
    })
  );
}

interface TocItem extends MarkdownHeading {
  children: TocItem[];
}

interface PluginPermissionsRouteData {
  id: string;
  entry: {
    body: string;
    data: { plugin?: string };
    filePath: string;
  };
  headings: MarkdownHeading[];
  toc?: {
    minHeadingLevel: number;
    maxHeadingLevel: number;
    items: TocItem[];
  };
}

export async function augmentPluginPermissionsToc(route: PluginPermissionsRouteData) {
  if (!route.toc || !route.id.includes('plugin/')) {
    return;
  }

  const source = await getEntrySource(route.entry);
  const plugin = route.entry.data.plugin ?? getPluginFromSource(source);

  if (!plugin || !source.includes('<PluginPermissions')) {
    return;
  }

  const pluginHeadings = await getPluginPermissionTocHeadings(plugin);

  if (pluginHeadings.length === 0 || hasTocItem(route.toc.items, pluginHeadings[0].slug)) {
    return;
  }

  route.headings = mergePluginHeadings(source, route.headings, pluginHeadings);
  route.toc.items = generateToc(route.headings, route.toc);
}

async function getEntrySource(entry: { body: string; filePath: string }) {
  try {
    return await fs.readFile(entry.filePath, 'utf-8');
  } catch {
    return entry.body;
  }
}

function getPluginFromSource(source: string) {
  const frontmatter = source.match(/^---\n([\s\S]*?)\n---/)?.[1];
  return frontmatter?.match(/^plugin:\s*['"]?([^'"\n]+)['"]?\s*$/m)?.[1]?.trim();
}

function mergePluginHeadings(
  body: string,
  pageHeadings: MarkdownHeading[],
  pluginHeadings: MarkdownHeading[]
) {
  const headings: MarkdownHeading[] = [];
  let pageHeadingIndex = 0;
  let codeFence: string | undefined;

  for (const line of body.split('\n')) {
    const fence = line.match(/^\s*(```|~~~)/)?.[1];

    if (fence) {
      codeFence = codeFence === fence ? undefined : (codeFence ?? fence);
      continue;
    }

    if (codeFence) {
      continue;
    }

    if (/^\s{0,3}#{2,6}\s+/.test(line) && pageHeadingIndex < pageHeadings.length) {
      headings.push(pageHeadings[pageHeadingIndex]);
      pageHeadingIndex += 1;
    }

    if (line.includes('<PluginPermissions')) {
      headings.push(...pluginHeadings);
    }
  }

  headings.push(...pageHeadings.slice(pageHeadingIndex));

  return headings;
}

function generateToc(
  headings: MarkdownHeading[],
  toc: { minHeadingLevel: number; maxHeadingLevel: number; items: TocItem[] }
) {
  const tocItems: TocItem[] = toc.items[0] ? [{ ...toc.items[0], children: [] }] : [];

  for (const heading of headings) {
    if (heading.depth < toc.minHeadingLevel || heading.depth > toc.maxHeadingLevel) {
      continue;
    }

    injectTocItem(tocItems, { ...heading, children: [] });
  }

  return tocItems;
}

function injectTocItem(items: TocItem[], item: TocItem): void {
  const lastItem = items.at(-1);

  if (!lastItem || lastItem.depth >= item.depth) {
    items.push(item);
    return;
  }

  injectTocItem(lastItem.children, item);
}

function hasTocItem(items: TocItem[], slug: string): boolean {
  return items.some((item) => item.slug === slug || hasTocItem(item.children, slug));
}

function htmlToText(html: string) {
  return html
    .replace(/<[^>]+>/g, '')
    .replaceAll('&amp;', '&')
    .replaceAll('&lt;', '<')
    .replaceAll('&gt;', '>')
    .replaceAll('&quot;', '"')
    .replaceAll('&#39;', "'")
    .trim();
}
