// generated by `tatu schema --emit-ts` — do not edit; regenerate from the runner

export interface TutorialManifest {
  /** relative path to the JSON Schema, so an editor validates hand edits */
  $schema?: string;
  /** bumped when the manifest shape changes; consumers assert on it */
  schemaVersion: number;
  id: string;
  title: string;
  /** true when produced outside the pinned container (`tatu check`); absent,
like platform, in the committed expected manifest (`tatu bless` strips
the run-environment fields) */
  advisory?: boolean;
  /** node-compatible platform tag: win32 / darwin / linux */
  platform?: string;
  steps: TutorialStepRecord[];
}

export interface TutorialStepRecord {
  id: string;
  task: string;
  mutations: MutationRecord[];
  preconditions: ResultRecord[];
  assertions: ResultRecord[];
}

export interface MutationRecord {
  /** the mutated file; its content after this step is `steps/<step>/<file>` */
  file?: string;
  /** true when the mutation created the file, so there is no `base/<file>`
and consumers render the whole file instead of a diff */
  created?: boolean;
  command?: string;
  cwd?: string;
}

export interface ResultRecord {
  kind: TutorialAssertionKind;
  command?: string;
  run?: string;
  status: Status;
}

export type TutorialAssertionKind = 'ipc-local' | 'ipc-acl' | 'shell';

export type Status = 'pass' | 'fail';

