// generated by `tatu schema --emit-ts` — do not edit; regenerate from the runner

export interface TutorialManifest {
  /** bumped when the manifest shape changes; consumers assert on it */
  schemaVersion: number;
  id: string;
  title: string;
  /** true when produced outside the pinned container (`tatu check`); absent,
like platform, in the committed expected manifest (`tatu bless` strips
the run-environment fields) */
  advisory?: boolean;
  /** node-compatible platform tag: win32 / darwin / linux */
  platform?: string;
  steps: TutorialStepRecord[];
}

export interface TutorialStepRecord {
  id: string;
  task: string;
  mutations: MutationRecord[];
  preconditions: ResultRecord[];
  assertions: ResultRecord[];
}

export interface MutationRecord {
  file?: string;
  /** base-relative unified diff; empty string when the overlay changed nothing */
  diff?: string;
  command?: string;
  cwd?: string;
}

export interface ResultRecord {
  kind: string;
  command?: string;
  run?: string;
  status: Status;
}

export type Status = 'pass' | 'fail';

