import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';
import { i18nSchema, docsSchema } from '@astrojs/starlight/schema';
import { docsLoader, i18nLoader } from '@astrojs/starlight/loaders';
import { topicSchema } from 'starlight-sidebar-topics/schema';
import { blogSchema } from 'starlight-blog/schema';

export const collections = {
  docs: defineCollection({
    loader: docsLoader(),
    schema: docsSchema({
      extend: (context) => blogSchema(context).merge(topicSchema),
    }),
  }),
  i18n: defineCollection({ loader: i18nLoader(), schema: i18nSchema() }),
  // Release notes, generated by packages/releases-site. Deliberately NOT part of
  // the `docs` collection: staying out of it is what stops Starlight building a
  // fallback copy of all ~2,800 pages for every locale. They are rendered by the
  // route in src/routes/release/, which only exists on production builds.
  releases: defineCollection({
    loader: glob({ base: './src/content/releases', pattern: '**/*.{md,mdx}' }),
    // Exactly the frontmatter the generator writes. Everything but `slug` is
    // handed to <StarlightPage> as-is, so the shapes must match Starlight's.
    // `slug` is ours: filenames like `v2.0.0.md` would mis-slugify on the dots.
    schema: z.object({
      slug: z.string(),
      title: z.string(),
      description: z.string().optional(),
      tableOfContents: z
        .union([
          z.literal(false),
          z.object({ minHeadingLevel: z.number(), maxHeadingLevel: z.number() }),
        ])
        .optional(),
      pagefind: z.boolean().optional(),
      editUrl: z.union([z.string(), z.literal(false)]).optional(),
      prev: z.boolean().optional(),
      next: z.boolean().optional(),
      head: z
        .array(
          z.object({
            tag: z.enum([
              'title',
              'base',
              'link',
              'style',
              'meta',
              'script',
              'noscript',
              'template',
            ]),
            attrs: z
              .record(z.string(), z.union([z.string(), z.boolean(), z.undefined()]))
              .optional(),
            content: z.string().optional(),
          })
        )
        .optional(),
    }),
  }),
};
