# Adapted from https://github.com/withastro/starlight/blob/main/.github/workflows/format.yml

name: 'Check formatting'

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: format-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-slim
    timeout-minutes: 10
    steps:
      - name: Check out code using Git
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v5

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - run: pnpm i

      - name: Check formatting
        run: pnpm format:check
