name: 'Sync Sponsors Data'

on:
  schedule:
    # daily
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-sponsors-data:
    name: Sync Sponsors Data
    runs-on: ubuntu-slim
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v5

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - run: pnpm i

      - name: sync-sponsors
        run: pnpm sync:sponsors
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: pnpm prettier src/data -w

   # tauri-docs PR
      - name: Git config
        run: |
          git config --global user.name "tauri-bot"
          git config --global user.email "tauri-bot@tauri.app"

      - name: Create pull request for updated docs
        id: cpr
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        if: github.event_name != 'pull_request' && github.event_name != 'push'
        with:
          token: ${{ secrets.ORG_TAURI_BOT_PAT }}
          commit-message: 'chore(docs): Update Sponsors Data'
          branch: ci/v2/update-sponsors
          title: Update Sponsors Data
          labels: 'bot'
          sign-commits: true
